### ISSUE TITLE
RRule until part as jcal is not parsable

### ISSUE THREAD

**Issue by GrahamLinagora** [fruux/sabre-vobject#259]
Hello,

I encountered a problem using sabre with jCal and recurring events.
When I try to create an event having a UNTIL part in its RRULE like :  `2016-02-27T22:00:00Z`
Sabre answers with a 500 with following error:
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.0.5</s:sabredav-version>
  <s:exception>LogicException</s:exception>
  <s:message>The supplied iCalendar datetime value is incorrect: 2016-02-27T22:00:00Z</s:message>
  <s:file>/var/www/vendor/sabre/vobject/lib/DateTimeParser.php</s:file>
  <s:line>40</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 /var/www/vendor/sabre/vobject/lib/DateTimeParser.php(188): Sabre\VObject\DateTimeParser::parseDateTime('2016-02-27T22:0...', Object(DateTimeZone))
#1 /var/www/vendor/sabre/vobject/lib/Recur/RRuleIterator.php(641): Sabre\VObject\DateTimeParser::parse('2016-02-27T22:0...', Object(DateTimeZone))
#2 /var/www/vendor/sabre/vobject/lib/Recur/RRuleIterator.php(36): Sabre\VObject\Recur\RRuleIterator-&gt;parseRRule(Array)
#3 /var/www/vendor/sabre/vobject/lib/Recur/EventIterator.php(186): Sabre\VObject\Recur\RRuleIterator-&gt;__construct(Array, Object(DateTime))
#4 /var/www/lib/CalDAV/Backend/Mongo.php(616): Sabre\VObject\Recur\EventIterator-&gt;__construct(Object(Sabre\VObject\Component\VCalendar), '75a9f34e-041f-4...')
#5 /var/www/lib/CalDAV/Backend/Mongo.php(227): ESN\CalDAV\Backend\Mongo-&gt;getDenormalizedData('BEGIN:VCALENDAR...')
#6 /var/www/vendor/sabre/dav/lib/CalDAV/Calendar.php(199): ESN\CalDAV\Backend\Mongo-&gt;createCalendarObject('561b7fe65fef200...', '75a9f34e-041f-4...', 'BEGIN:VCALENDAR...')
#7 /var/www/vendor/sabre/dav/lib/DAV/Server.php(1036): Sabre\CalDAV\Calendar-&gt;createFile('75a9f34e-041f-4...', 'BEGIN:VCALENDAR...')
#8 /var/www/vendor/sabre/dav/lib/DAV/CorePlugin.php(525): Sabre\DAV\Server-&gt;createFile('calendars/54be3...', Resource id #5, NULL)
#9 [internal function]: Sabre\DAV\CorePlugin-&gt;httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#10 /var/www/vendor/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#11 /var/www/vendor/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter-&gt;emit('method:PUT', Array)
#12 /var/www/vendor/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#13 /var/www/server.php(150): Sabre\DAV\Server-&gt;exec()
#14 {main}</s:stacktrace>
</d:error>
```

According to Jcal RFC (https://tools.ietf.org/html/rfc7265#section-3.1), the date format I send is correct. On the other hand, iCalendar does not support such dates and only supports `YYYYMMDDTHHMMSS` date format.

For now, sabre-vobject only checks the until part of the jcal against the iCalendar date format which is what makes my request fail.
I think that sabre-vobject should accept jCal complaint date formats when receiving json and parse as it currently does when receiving an iCalendar.

I am working on a patch for this, and will issue a PR as soon as it works well.

Full sent Jcal for information:
```javascript
["vevent",[["uid",{},"text","75a9f34e-041f-45fb-a174-5c30b5c3b791"],["summary",{},"text","No title"],["organizer",{"cn":"robert pipo"},"cal-address","mailto:robert@pipo.com"],["dtstart",{"tzid":"Europe/Berlin"},"date-time","2015-10-21T18:00:00"],["dtend",{"tzid":"Europe/Berlin"},"date-time","2015-10-21T19:00:00"],["transp",{},"text","OPAQUE"],["rrule",{},"recur",{"freq":"MONTHLY","interval":[3],"until":"2016-02-27T22:00:00Z"}]],[]]
```

**Comment by evert** [comment]
Definitely sounds like a bug. A PR is very appreciated =) The key is that it should probably get fixed in the `setJsonValue()` function in `Sabre\VObject\Property\ICalendar\Recur`.

**Comment by GrahamLinagora** [comment]
PR opened : https://github.com/fruux/sabre-vobject/pull/261
