### ISSUE TITLE
Undefined variable: stripTimezones

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-vobject#278]
Somewhere between 9a0f531 and 91060b9 (https://github.com/fruux/sabre-vobject/compare/9a0f531...91060b9) there seems to be a change that affects the ICSExportPlugin.

With the more recent vobject version the following error occurs:
`'Undefined variable: stripTimezones' in /sabre/vobject/lib/Component/VCalendar.php:314`

Will update this issue as soon as I get around to dig into this a bit further.

**Stack trace:**

```
#0 /opt/app/vendor/sabre/vobject/lib/Component/VCalendar.php(314): Application->errorHandler(8, 'Undefined varia...', '/...', 314, Array)
#1 /opt/app/vendor/sabre/vobject/lib/Component/VCalendar.php(344): Sabre\VObject\Component\VCalendar->Sabre\VObject\Component\{closure}(Object(Sabre\VObject\Component\VEvent))
#2 /opt/app/vendor/sabre/dav/lib/CalDAV/ICSExportPlugin.php(246): Sabre\VObject\Component\VCalendar->expand(Object(DateTime), Object(DateTime), Object(DateTimeZone))
#3 /opt/app/lib/DAV/Calendar/MyICSExportPlugin.php(259): Sabre\CalDAV\MyICSExportPlugin->generateResponse('calendars/foo...', Object(DateTime), Object(DateTime), true, 'VEVENT', 'application/cal...', Array, Object(Sabre\HTTP\Response))
#4 /opt/app/lib/DAV/Calendar/MyICSExportPlugin.php(205): MyApp\Calendar\MyICSExportPlugin->generateResponse('calendars/foo...', Object(DateTime), Object(DateTime), true, 'VEVENT', 'application/cal...', Array, Object(Sabre\HTTP\Response))
#5 /opt/app/lib/DAV/Calendar/MyICSExportPlugin.php(88): MyApp\Calendar\ICSExportPlugin->generateAllCalendars(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), false)
#6 [internal function]: MyApp\Calendar\ICSExportPlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#7 /opt/app/vendor/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#8 /opt/app/vendor/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:GET', Array)
#9 /opt/app/vendor/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#10 /opt/app/lib/DAV/Server.php(205): Sabre\DAV\Server->exec()
#11 /opt/app/public/server.php(14): MyApp\Server->exec() #12 {main}

**Comment by DominikTo** [comment]
It's probably related to afa5cbf04d1fe1687ff365c3a4da698246cb844d.

**Comment by staabm** [comment]
Did you try `git bisect` to find the commit which introduced the error?

**Comment by Hywan** [comment]
@DominikTo See https://github.com/fruux/sabre-vobject/commit/afa5cbf04d1fe1687ff365c3a4da698246cb844d#commitcomment-14875789.

**Comment by Hywan** [comment]
@DominikTo PR is ready: https://github.com/fruux/sabre-vobject/pull/279 :-).

**Comment by DominikTo** [comment]
Haha, I just wanted to start looking into this again, looks like I am too late. :+1:
